# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  burotoast.nl:
    site_hosts:
      - canonical: mijnsite.test
        redirects:
          - www.mijnsite.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@mijnsite.test
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
